version: '3.8'

services:

  postgres:
    image: postgres:17.2
    container_name: postgres_container
    restart: unless-stopped
    volumes:
    - postgres_data:/var/lib/postgresql/data/pgdata
    - ./dat/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
volumes:
  postgres_data: